### ISSUE TITLE
antaris

### ISSUE THREAD

**Issue by sandub** [Thisishowwedoit/2Moons-Revolution-2.0#17]
USER ERROR
Message: Call to undefined function getUniverse()
File: /includes/common.php
Line: 108
URL: http://antaris.esy.es/
PHP-Version: 7.0.16
PHP-API: litespeed
MySQL-Client-Version: mysqlnd 5.0.12-dev - 20150407 - $Id: b5c5906d452ec590732a93b051f3827e02749b83 $
2Moons Version: UNKNOWN
Debug Backtrace:
#0 /index.php(35): require()
#1 {main}

**Comment by sandub** [comment]
Message: Declaration of template::display($file) should be compatible with Smarty_Internal_TemplateBase::display($template = NULL, $cache_id = NULL, $compile_id = NULL, $parent = NULL)
File: /includes/classes/class.template.php
Line: 32
URL: http://2moons-revolution.esy.es/
PHP-Version: 7.0.16
PHP-API: litespeed
MySQL-Cleint-Version: mysqlnd 5.0.12-dev - 20150407 - $Id: b5c5906d452ec590732a93b051f3827e02749b83 $
2Moons Version: UNKNOWN
Debug Backtrace:
#0 /includes/classes/class.template.php(32): errorHandler(2, 'Declaration of ...', 'FILEPATH ...', 32, Array)
#1 /includes/common.php(75): require('FILEPATH ...')
#2 /index.php(35): require('FILEPATH ...')
#3 {main}
